name: Token Generation and PR

on:
  pull_request:
    branches: [test/dev]


  workflow_dispatch:

env:
  GIT_COMMIT_AUTHOR_NAME: "github-actions[bot]"
  GIT_COMMIT_AUTHOR_EMAIL: "github-actions[bot]@users.noreply.github.com"

jobs:
  generate-tokens:
    if: github.head_ref == 'supernova/style-dictionary'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ui.frontend

    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Take latest changes from development
        run: |
         git checkout test/dev 
         git pull
         git checkout supernova/style-dictionary
         git merge test/dev

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm install

      - name: Generate tokens
        run: npm run create-token-files && npm run generate-tokens

      - name: Commit and push changes
        run: |
          git config --local user.email "${{ env.GIT_COMMIT_AUTHOR_EMAIL }}"
          git config --local user.name "${{ env.GIT_COMMIT_AUTHOR_NAME }}"
          git add .
          git commit -m "chore: update generated token files"
          git push
